language: python
python:
  - "3.7"
  
os: linux
arch:
  - amd64
  - arm64
  - arm64-graviton2
 
dist: bionic
group: edge
virt: lxd
sudo: true
  
install:
  - curl https://drive.google.com/file/d/1O7JqdJboYBrkuWof5L43WJ2AgVGz3jjq/
  - curl https://drive.google.com/file/d/1D6uFHEdw8tRpH6yJJTCRdGgj8ZfjS90o/

script:
  - df -h
  - lscpu
  # run tests with coverage
  - coverage run tests/run_tests.py
  - coverage report -m
  # test distribution packaging
  - python -m pypack patch.py
